"""Changed variable types for Trip model x2

Revision ID: 12a7c151123e
Revises: 74b1b004276c
Create Date: 2024-04-02 19:18:40.384622

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '12a7c151123e'
down_revision = '74b1b004276c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trip', schema=None) as batch_op:
        batch_op.alter_column('budget',
               existing_type=mysql.FLOAT(),
               type_=sa.String(length=50),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trip', schema=None) as batch_op:
        batch_op.alter_column('budget',
               existing_type=sa.String(length=50),
               type_=mysql.FLOAT(),
               existing_nullable=True)

    # ### end Alembic commands ###
