"""increased user preference lengths again

Revision ID: 256866aae110
Revises: 825218079323
Create Date: 2024-04-10 15:21:22.810934

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '256866aae110'
down_revision = '825218079323'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('fav_activities',
               existing_type=mysql.VARCHAR(length=300),
               type_=sa.String(length=800),
               existing_nullable=True)
        batch_op.alter_column('fav_foods',
               existing_type=mysql.VARCHAR(length=300),
               type_=sa.String(length=800),
               existing_nullable=True)
        batch_op.alter_column('fav_shopping',
               existing_type=mysql.VARCHAR(length=300),
               type_=sa.String(length=800),
               existing_nullable=True)
        batch_op.alter_column('fav_accomodations',
               existing_type=mysql.VARCHAR(length=300),
               type_=sa.String(length=800),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('fav_accomodations',
               existing_type=sa.String(length=800),
               type_=mysql.VARCHAR(length=300),
               existing_nullable=True)
        batch_op.alter_column('fav_shopping',
               existing_type=sa.String(length=800),
               type_=mysql.VARCHAR(length=300),
               existing_nullable=True)
        batch_op.alter_column('fav_foods',
               existing_type=sa.String(length=800),
               type_=mysql.VARCHAR(length=300),
               existing_nullable=True)
        batch_op.alter_column('fav_activities',
               existing_type=sa.String(length=800),
               type_=mysql.VARCHAR(length=300),
               existing_nullable=True)

    # ### end Alembic commands ###
