"""Preference length to 1000

Revision ID: 4f2fbd17b1a6
Revises: 749e0ac5eff2
Create Date: 2024-04-12 18:21:00.859691

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4f2fbd17b1a6'
down_revision = '749e0ac5eff2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('fav_activities',
               existing_type=mysql.VARCHAR(length=300),
               type_=sa.String(length=1000),
               existing_nullable=True)
        batch_op.alter_column('fav_foods',
               existing_type=mysql.VARCHAR(length=300),
               type_=sa.String(length=1000),
               existing_nullable=True)
        batch_op.alter_column('fav_shopping',
               existing_type=mysql.VARCHAR(length=300),
               type_=sa.String(length=1000),
               existing_nullable=True)
        batch_op.alter_column('fav_accomodations',
               existing_type=mysql.VARCHAR(length=300),
               type_=sa.String(length=1000),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('fav_accomodations',
               existing_type=sa.String(length=1000),
               type_=mysql.VARCHAR(length=300),
               existing_nullable=True)
        batch_op.alter_column('fav_shopping',
               existing_type=sa.String(length=1000),
               type_=mysql.VARCHAR(length=300),
               existing_nullable=True)
        batch_op.alter_column('fav_foods',
               existing_type=sa.String(length=1000),
               type_=mysql.VARCHAR(length=300),
               existing_nullable=True)
        batch_op.alter_column('fav_activities',
               existing_type=sa.String(length=1000),
               type_=mysql.VARCHAR(length=300),
               existing_nullable=True)

    # ### end Alembic commands ###
