"""Database columns for all generated trip data

Revision ID: 707b8ff91067
Revises: da1e965c07bc
Create Date: 2024-04-16 21:52:19.090469

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '707b8ff91067'
down_revision = 'da1e965c07bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gender', sa.String(length=5), nullable=True))
        batch_op.add_column(sa.Column('age', sa.String(length=5), nullable=True))
        batch_op.add_column(sa.Column('interests', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('accommodations', sa.String(length=5), nullable=True))
        batch_op.add_column(sa.Column('transportation', sa.String(length=5), nullable=True))
        batch_op.drop_column('fav_foods')
        batch_op.drop_column('fav_activities')
        batch_op.drop_column('fav_shopping')
        batch_op.drop_column('fav_accomodations')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fav_accomodations', mysql.JSON(), nullable=True))
        batch_op.add_column(sa.Column('fav_shopping', mysql.JSON(), nullable=True))
        batch_op.add_column(sa.Column('fav_activities', mysql.JSON(), nullable=True))
        batch_op.add_column(sa.Column('fav_foods', mysql.JSON(), nullable=True))
        batch_op.drop_column('transportation')
        batch_op.drop_column('accommodations')
        batch_op.drop_column('interests')
        batch_op.drop_column('age')
        batch_op.drop_column('gender')

    # ### end Alembic commands ###
