"""Added Trip model

Revision ID: 74b1b004276c
Revises: 240056df8885
Create Date: 2024-04-02 14:01:07.012162

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74b1b004276c'
down_revision = '240056df8885'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trip',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('dates', sa.String(length=100), nullable=False),
    sa.Column('trip_length', sa.Integer(), nullable=True),
    sa.Column('budget', sa.Float(), nullable=True),
    sa.Column('city_description', sa.Text(), nullable=True),
    sa.Column('city_slogan', sa.String(length=100), nullable=True),
    sa.Column('activities', sa.JSON(), nullable=True),
    sa.Column('landmarks', sa.JSON(), nullable=True),
    sa.Column('shops', sa.JSON(), nullable=True),
    sa.Column('foods', sa.JSON(), nullable=True),
    sa.Column('hotels', sa.JSON(), nullable=True),
    sa.Column('activities_images', sa.JSON(), nullable=True),
    sa.Column('landmarks_images', sa.JSON(), nullable=True),
    sa.Column('shops_images', sa.JSON(), nullable=True),
    sa.Column('foods_images', sa.JSON(), nullable=True),
    sa.Column('hotels_images', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trip')
    # ### end Alembic commands ###
