"""Larger p preferences capacity

Revision ID: 77817f3ddccf
Revises: 256866aae110
Create Date: 2024-04-12 17:38:12.039110

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '77817f3ddccf'
down_revision = '256866aae110'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('fav_activities',
               existing_type=mysql.VARCHAR(length=800),
               type_=sa.String(length=2000),
               existing_nullable=True)
        batch_op.alter_column('fav_foods',
               existing_type=mysql.VARCHAR(length=800),
               type_=sa.String(length=2000),
               existing_nullable=True)
        batch_op.alter_column('fav_shopping',
               existing_type=mysql.VARCHAR(length=800),
               type_=sa.String(length=2000),
               existing_nullable=True)
        batch_op.alter_column('fav_accomodations',
               existing_type=mysql.VARCHAR(length=800),
               type_=sa.String(length=2000),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('fav_accomodations',
               existing_type=sa.String(length=2000),
               type_=mysql.VARCHAR(length=800),
               existing_nullable=True)
        batch_op.alter_column('fav_shopping',
               existing_type=sa.String(length=2000),
               type_=mysql.VARCHAR(length=800),
               existing_nullable=True)
        batch_op.alter_column('fav_foods',
               existing_type=sa.String(length=2000),
               type_=mysql.VARCHAR(length=800),
               existing_nullable=True)
        batch_op.alter_column('fav_activities',
               existing_type=sa.String(length=2000),
               type_=mysql.VARCHAR(length=800),
               existing_nullable=True)

    # ### end Alembic commands ###
