"""Adding user preferences to user model

Revision ID: 7a199159634a
Revises: 248e7b7ed6b4
Create Date: 2024-04-10 13:15:22.274639

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7a199159634a'
down_revision = '248e7b7ed6b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fav_activities', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('fav_foods', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('fav_shopping', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('fav_accomodations', sa.String(length=100), nullable=True))
        batch_op.drop_column('gender')
        batch_op.drop_column('transportation')
        batch_op.drop_column('accommodations')
        batch_op.drop_column('age')
        batch_op.drop_column('interests')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('interests', mysql.VARCHAR(length=10), nullable=True))
        batch_op.add_column(sa.Column('age', mysql.VARCHAR(length=5), nullable=True))
        batch_op.add_column(sa.Column('accommodations', mysql.VARCHAR(length=5), nullable=True))
        batch_op.add_column(sa.Column('transportation', mysql.VARCHAR(length=5), nullable=True))
        batch_op.add_column(sa.Column('gender', mysql.VARCHAR(length=5), nullable=True))
        batch_op.drop_column('fav_accomodations')
        batch_op.drop_column('fav_shopping')
        batch_op.drop_column('fav_foods')
        batch_op.drop_column('fav_activities')

    # ### end Alembic commands ###
