"""Fixing migration issues?

Revision ID: c7091f5ce772
Revises: 707b8ff91067
Create Date: 2024-04-18 16:23:56.136272

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c7091f5ce772'
down_revision = '707b8ff91067'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trip', schema=None) as batch_op:
        batch_op.drop_column('generated_hotels')
        batch_op.drop_column('generated_shops')
        batch_op.drop_column('generated_landmarks')
        batch_op.drop_column('generated_activities')
        batch_op.drop_column('generated_foods')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fav_activities', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('fav_foods', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('fav_shopping', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('fav_accomodations', sa.JSON(), nullable=True))
        batch_op.drop_column('interests')
        batch_op.drop_column('gender')
        batch_op.drop_column('age')
        batch_op.drop_column('accommodations')
        batch_op.drop_column('transportation')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('transportation', mysql.VARCHAR(length=5), nullable=True))
        batch_op.add_column(sa.Column('accommodations', mysql.VARCHAR(length=5), nullable=True))
        batch_op.add_column(sa.Column('age', mysql.VARCHAR(length=5), nullable=True))
        batch_op.add_column(sa.Column('gender', mysql.VARCHAR(length=5), nullable=True))
        batch_op.add_column(sa.Column('interests', mysql.VARCHAR(length=10), nullable=True))
        batch_op.drop_column('fav_accomodations')
        batch_op.drop_column('fav_shopping')
        batch_op.drop_column('fav_foods')
        batch_op.drop_column('fav_activities')

    with op.batch_alter_table('trip', schema=None) as batch_op:
        batch_op.add_column(sa.Column('generated_foods', mysql.JSON(), nullable=True))
        batch_op.add_column(sa.Column('generated_activities', mysql.JSON(), nullable=True))
        batch_op.add_column(sa.Column('generated_landmarks', mysql.JSON(), nullable=True))
        batch_op.add_column(sa.Column('generated_shops', mysql.JSON(), nullable=True))
        batch_op.add_column(sa.Column('generated_hotels', mysql.JSON(), nullable=True))

    # ### end Alembic commands ###
