"""shortening string length for user preferences

Revision ID: c8dd93640730
Revises: 77817f3ddccf
Create Date: 2024-04-12 18:13:54.098613

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c8dd93640730'
down_revision = '77817f3ddccf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('fav_activities',
               existing_type=mysql.VARCHAR(length=2000),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.alter_column('fav_foods',
               existing_type=mysql.VARCHAR(length=2000),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.alter_column('fav_shopping',
               existing_type=mysql.VARCHAR(length=2000),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.alter_column('fav_accomodations',
               existing_type=mysql.VARCHAR(length=2000),
               type_=sa.String(length=100),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('fav_accomodations',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=2000),
               existing_nullable=True)
        batch_op.alter_column('fav_shopping',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=2000),
               existing_nullable=True)
        batch_op.alter_column('fav_foods',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=2000),
               existing_nullable=True)
        batch_op.alter_column('fav_activities',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=2000),
               existing_nullable=True)

    # ### end Alembic commands ###