"""columns for all generated content

Revision ID: da1e965c07bc
Revises: 09e459a06dc5
Create Date: 2024-04-16 19:22:26.763277

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da1e965c07bc'
down_revision = '09e459a06dc5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trip', schema=None) as batch_op:
        batch_op.add_column(sa.Column('generated_activities', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('generated_landmarks', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('generated_shops', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('generated_foods', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('generated_hotels', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trip', schema=None) as batch_op:
        batch_op.drop_column('generated_hotels')
        batch_op.drop_column('generated_foods')
        batch_op.drop_column('generated_shops')
        batch_op.drop_column('generated_landmarks')
        batch_op.drop_column('generated_activities')

    # ### end Alembic commands ###